//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public int id { get; set; }
        public string name { get; set; }
        public string coords { get; set; }
        public Nullable<int> start_year { get; set; }
        public string url_name { get; set; }
        public string country { get; set; }
        public string country_state { get; set; }
    }
}
