//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class line
    {
        public int id { get; set; }
        public Nullable<int> city_id { get; set; }
        public string name { get; set; }
        public string url_name { get; set; }
        public string color { get; set; }
        public Nullable<int> system_id { get; set; }
        public Nullable<int> transport_mode_id { get; set; }
    }
}
