//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database : DbContext
    {
        public Database()
            : base("name=Database")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<station_lines> station_lines { get; set; }
        public virtual DbSet<station> stations { get; set; }
        public virtual DbSet<system> systems { get; set; }
        public virtual DbSet<track_lines> track_lines { get; set; }
        public virtual DbSet<track> tracks { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<line> lines { get; set; }
    }
}
