//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class station
    {
        public int id { get; set; }
        public string name { get; set; }
        public string geometry { get; set; }
        public Nullable<int> buildstart { get; set; }
        public Nullable<int> opening { get; set; }
        public Nullable<int> closure { get; set; }
        public int city_id { get; set; }
    }
}
