//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class track_lines
    {
        public int id { get; set; }
        public int section_id { get; set; }
        public int line_id { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
        public int city_id { get; set; }
    }
}
